### ISSUE TITLE
Hang dumps not uploaded on Azure pipelines for MacOS

### ISSUE THREAD

**Issue by SteveBush** [AArnott/Library.Template#167]
Hang dumps are not being uploaded on MacOS Azure pipeline agents.  GitHub Actions work fine.  When I open a TRX, the following dialog shows the relative path for a macOS hang dump (ignore the downloads folder prefix).

![image](https://user-images.githubusercontent.com/2798266/174506511-8057c220-d737-4e1d-87a1-f60b6d07c43c.png)

**Comment by AArnott** [comment]
Hang dumps aren't even *created* on macOS agents, [by the look of it](https://dev.azure.com/andrewarnott/OSS/_build/results?buildId=6672&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=e296fa38-21f9-5a00-2668-88de28826a74). Errors about the platform not supporting it. I wonder what GitHub Actions could possibly do differently since this appears to be a limitation in the `dotnet test` tooling.

Dmp files *are* created on linux and Windows, but I don't see them included in any published artifact. I know I had at least _that_ working in the past. I'll have to investigate what happened and get that fixed.
