### ISSUE TITLE
Verified CodeCov download requires installation of gpg

### ISSUE THREAD

**Issue by SteveBush** [AArnott/Library.Template#168]
I self-host a Windows Azure pipeline agent so that I can see what's happening with the build system using a local PC.  To verify the download of the codecov binary, I needed to install GPG4Win on my Windows agent host.  I could have set the AllowSkipVerify switch to skip verification.

All other tools are downloaded as part of the build (dotnet, ProcDump, Nuget, etc.).  Unfortunately, I understand it's a chicken and egg problem as GPG is used to verify a download.  

A suggestion is to update the project readme with instructions on how to download GPG for self-hosted agents.  Also, maybe a list of build tool requirements that aren't part of the Azure or GitHub Actions agent tool chain.

**Comment by AArnott** [comment]
I suppose gpg installation instructions will vary by agent OS. I don't know how gpg doesn't exist on your local build agent since gpg comes with Git for Windows. Maybe it just isn't on your path? 
Documenting the tools the pipeline assumes are already on the agent seems like a fine idea, although since I only test on Hosted agents, keeping that document up will likely be issue-based like this one. Ideally we could download whatever we need so if there's a chocolatey or other package with gpg that's great too.
